### ISSUE TITLE
Allow for encrypted AMI volumes

### ISSUE THREAD

**Issue by KnownSubset** [coreos/scripts#406]
There is no easy way to have an EC2 instance with an encrypted volume when booting up from the CoreOS provided AMIs.  I suggest that we modify the [build script](https://github.com/coreos/scripts/blob/master/oem/ami/build_ebs_on_ec2.sh) for AMIs so that an additional AMI is built per virtualization type with an encrypted volume.  

There is a reduced list of instances available that can run the additional AMIs with encryption enabled, as not all instances support EBS encryption.

**Comment by KnownSubset** [comment]
Since PR #400 was merged in a couple weeks back.  It seems that your current build process ([import.sh](../tree/master/oem/ami/import.sh)) still does support encrypted root devices for your AMI images.  It is still possible to create an encrypted volume/snapshot, but it would entail copying the data over from the imported volume to the encrypted volume and registering additional AMIs. 

I could create a PR for creating the AMIs with encrypted root devices, but I don't know what other pieces would need to be touched to have the AMIs show up, or hide them, on the [CoreOS EC2 page](https://coreos.com/docs/running-coreos/cloud-providers/ec2/).

**Comment by marineam** [comment]
According to the Amazon documentation it is simply not possible for us to publish public AMIs with encrypted volumes:

> Public or shared snapshots of encrypted volumes are not supported, because other accounts would not be able to decrypt your data.

and

> Encrypted boot volumes are not supported at this time.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html

I presume the warning about boot volumes is simply because no public AMIs can provide encrypted volumes. If that's a white lie and your recommendation works great, but due to the way EBS encryption keys are managed you are stuck with creating the AMIs yourself.
